//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtuosoSkos {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SkosAndStoreSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SkosAndStoreSettings defaultInstance = ((SkosAndStoreSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SkosAndStoreSettings())));
        
        public static SkosAndStoreSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.w3.org/2004/02/skos/core#")]
        public string skosCore {
            get {
                return ((string)(this["skosCore"]));
            }
            set {
                this["skosCore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string skosLanguage {
            get {
                return ((string)(this["skosLanguage"]));
            }
            set {
                this["skosLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.w3.org/2001/XMLSchema#")]
        public string xmlSchema {
            get {
                return ((string)(this["xmlSchema"]));
            }
            set {
                this["xmlSchema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("prefLabel, altLabel, scopeNote, hiddenLabel")]
        public string searchPredicates {
            get {
                return ((string)(this["searchPredicates"]));
            }
            set {
                this["searchPredicates"] = value;
            }
        }
    }
}
